# Default values for sanfran.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

k8s:
  type: "minikube"
nodeJS:
  tag: 0.1
router:
  tag: 0.1
  instances: 1
controller:
  tag: 0.1
  poolSize: 1
  instances: 1
sidecar:
  tag: 0.1
fnapi:
  tag: 0.1
fnapiCache:
  tag: 0.1
  instances: 1
