# Default values for sanfran.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

k8s:
  services:
    type: "ClusterIP"
nodeJS:
  tag: 0.3
router:
  tag: 0.3
  instances: 1
apiProxy:
  tag: 0.3
  instances: 1
controller:
  tag: 0.3
  poolSize: 1
  instances: 1
sidecar:
  tag: 0.3
fnapi:
  tag: 0.3
  storage:
    size: 10Gi
fnstore:
  tag: "RELEASE.2017-11-22T19-55-46Z"
  storage:
    size: 10Gi
fnstoreCache:
  tag: 0.3
  instances: 1
builder:
  tag: 0.3
  instances: 1
janitor:
  tag: 0.3
  schedule: "*/30 * * * *"