# Default values for sanfran.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

k8s:
  services:
    type: "ClusterIP"
nodeJS:
  tag: 0.2
router:
  tag: 0.2
  instances: 1
apiProxy:
  tag: 0.2
  instances: 1
controller:
  tag: 0.2
  poolSize: 1
  instances: 1
sidecar:
  tag: 0.2
fnapi:
  tag: 0.2
  persistence:
    size: 10Gi
fnstore:
  mode: standalone
  replicas: 1
  accessKey: pooraccesskey
  secretKey: poorsecretkey
  serviceType: ClusterIP
  persistence:
    size: 10Gi
fnstoreCache:
  tag: 0.2
  instances: 1
builder:
  tag: 0.2
  instances: 1
janitor:
  tag: 0.2
  schedule: "*/30 * * * *"