## Functions API Code Cache Service

apiVersion: v1
kind: Service
metadata:
  name: sanfran-fnapi-cache-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: sanfran-fnapi-cache

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sanfran-fnapi-cache
spec:
  selector:
    matchLabels:
      app: sanfran-fnapi-cache
  replicas: {{ .Values.fnapiCache.instances }}
  template:
    metadata:
      labels:
        app: sanfran-fnapi-cache
    spec:
      securityContext:
        #runAsNonRoot: true
        #runAsUser: 65534
      containers:
        - name: sanfran-fnapi-cache
          image: sanfran/fnapi-cache:{{ .Values.fnapiCache.tag }}
          securityContext:
            #allowPrivilegeEscalation: false
            #readOnlyRootFilesystem: true
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: cache-volume
              mountPath: /var/lib/nginx/cache
          env:
            - name: PROXY_HOST
              value: sanfran-fnapi-service.{{ .Release.Namespace }}.svc.cluster.local:80
      volumes:
        - name: cache-volume
          emptyDir:
            medium: "Memory"
            sizeLimit: "100Mi"