# Default values for sanfran.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

router:
  tag: v1
  instances: 1
controller:
  tag: v1
  poolSize: 3
  instances: 1
sidecar:
  tag: v1
fnapi:
  tag: v1
fnapiCache:
  tag: v1
  instances: 1
