## Builder

{{ $fnstoreSecret := printf "%s-%s" .Release.Name "fnstore-user" }}

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sanfran-builder
spec:
  selector:
    matchLabels:
      app: sanfran-builder
  replicas:  {{ .Values.builder.instances }}
  template:
    metadata:
      labels:
        app: sanfran-builder
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: sanfran-builder
          image: dosco/sanfran-builder:{{ .Values.builder.tag }}
          securityContext:
            #allowPrivilegeEscalation: false
            #readOnlyRootFilesystem: true
          ports:
            - name: grpc
              containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: SANFRAN_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SANFRAN_HELM_RELEASE
              value: {{ .Release.Name }}
            - name: SANFRAN_FNSTORE_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: {{ $fnstoreSecret }}
                  key: accesskey
            - name: SANFRAN_FNSTORE_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: {{ $fnstoreSecret }}
                  key: secretkey
      volumes:
        - name: data
          emptyDir:
            medium: "Memory"
            sizeLimit: "100Mi"
