## Controller

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sanfran.fullname" . }}-cm
  labels:
    app: {{ template "sanfran.fullname" . }}-cm
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  controller.poolsize: {{ .Values.controller.poolSize | quote }}

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "sanfran.fullname" . }}
  labels:
    app: {{ template "sanfran.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ template "sanfran.fullname" . }}
  replicas: {{ .Values.controller.instances }}
  template:
    metadata:
      labels:
        app: {{ template "sanfran.fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: sanfran-controller
          image: dosco/sanfran-controller:{{ .Values.controller.tag }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          ports:
            - name: grpc
              containerPort: 8080
          env:
            - name: SANFRAN_FN_LANG_IMAGE
              value: "dosco/sanfran-nodejs:{{ .Values.nodeJS.tag }}"
            - name: SANFRAN_SIDECAR_IMAGE
              value: "dosco/sanfran-sidecar:{{ .Values.sidecar.tag }}"
            - name: SANFRAN_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SANFRAN_HELM_RELEASE
              value: {{ .Release.Name }}
            - name: SANFRAN_CONTROLLER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SANFRAN_CONTROLLER_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          volumeMounts:
            - name: config-volume
              mountPath: /etc/sanfran-config
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "sanfran.fullname" . }}-cm