## Functions API Service

apiVersion: v1
kind: Service
metadata:
  name: sanfran-fnapi-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: grpc
    port: 8080
  selector:
    app: sanfran-fnapi

---
{{ $fnstoreSecret := printf "%s-%s" .Release.Name "fnstore-user" }}

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: fnapi
spec:
  selector:
    matchLabels:
      app: sanfran-fnapi
  serviceName: "sanfran-fnapi-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: sanfran-fnapi
    spec:
      terminationGracePeriodSeconds: 5
      securityContext:
        #runAsNonRoot: true
        #runAsUser: 65534
      containers:
        - name: sanfran-fnapi
          image: dosco/sanfran-fnapi:{{ .Values.fnapi.tag }}
          securityContext:
            #allowPrivilegeEscalation: false
            #readOnlyRootFilesystem: true
          ports:
            - name: grpc
              containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: SANFRAN_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SANFRAN_HELM_RELEASE
              value: {{ .Release.Name }}
            - name: SANFRAN_FNSTORE_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: {{ $fnstoreSecret }}
                  key: accesskey
            - name: SANFRAN_FNSTORE_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: {{ $fnstoreSecret }}
                  key: secretkey
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          {{- if .Values.fnapi.persistence.storageClass }}
          volume.beta.kubernetes.io/storage-class: {{ .Values.fnapi.persistence.storageClass }}
          {{- else }}
          volume.alpha.kubernetes.io/storage-class: default
          {{- end }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.fnapi.persistence.size }}