## Functions API Service

apiVersion: v1
kind: Service
metadata:
  name: {{ template "sanfran.fullname" . }}-svc
  labels:
    app: {{ template "sanfran.fullname" . }}-svc
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: grpc
    port: 8080
  selector:
    app: {{ template "sanfran.fullname" . }}

---
{{ $fnstoreSecret := printf "%s-%s" .Release.Name "fnstore-user" }}

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "sanfran.fullname" . }}
  labels:
    app: {{ template "sanfran.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ template "sanfran.fullname" . }}
  serviceName: {{ template "sanfran.fullname" . }}-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "sanfran.fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      terminationGracePeriodSeconds: 5
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: sanfran-fnapi
          image: dosco/sanfran-fnapi:{{ .Values.fnapi.tag }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          ports:
            - name: grpc
              containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: SANFRAN_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SANFRAN_HELM_RELEASE
              value: {{ .Release.Name }}
            - name: SANFRAN_FNSTORE_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: {{ $fnstoreSecret }}
                  key: accesskey
            - name: SANFRAN_FNSTORE_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: {{ $fnstoreSecret }}
                  key: secretkey
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          {{- if .Values.fnapi.persistence.storageClass }}
          volume.beta.kubernetes.io/storage-class: {{ .Values.fnapi.persistence.storageClass }}
          {{- else }}
          volume.alpha.kubernetes.io/storage-class: default
          {{- end }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.fnapi.persistence.size }}