## Functions API Service

apiVersion: v1
kind: Service
metadata:
  name: sanfran-fnapi-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: grpc
    port: 8080
  - name: http
    port: 8081
  selector:
    app: sanfran-fnapi

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: fnapi
spec:
  selector:
    matchLabels:
      app: sanfran-fnapi
  serviceName: "sanfran-fnapi-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: sanfran-fnapi
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        #runAsNonRoot: true
        #runAsUser: 65534
      containers:
        - name: sanfran-fnapi
          image: dosco/sanfran-fnapi:{{ .Values.fnapi.tag }}
          securityContext:
            #allowPrivilegeEscalation: false
            #readOnlyRootFilesystem: true
          ports:
            - name: grpc
              containerPort: 8080
            - name: http
              containerPort: 8081
          {{- if eq .Values.k8s.type "gke" }}
          {{- include "fnapi-volume-mounts" . | indent 10 }}
          {{- end}}

      {{- if eq .Values.k8s.type "gke" }}
      {{- include "fnapi-volumes" . | indent 6 }}
      {{- end}}