## Functions API Code Cache Service

{{ $fnstoreService := printf "%s-fnstore-svc.%s.svc.cluster.local:9000" .Release.Name .Release.Namespace }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sanfran.fullname" . }}-cm
  labels:
    app: {{ template "sanfran.fullname" . }}-cm
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  nginx.conf: |-
    pid /dev/null;
    worker_processes auto;
    events {
      worker_connections 1024;
    }

    http {
      proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=fncache:8m max_size=50m inactive=30m use_temp_path=off;

      server {
        access_log /dev/null;
        error_log /dev/null;

        listen 8080;

        location / {
          set $proxy_host '{{ $fnstoreService }}';

          expires -1;
          add_header Cache-Control "no-store";

          resolver 10.0.0.10 valid=10s ipv6=off;
          resolver_timeout 5s;

          proxy_cache fncache;
          proxy_pass http://$proxy_host;
          proxy_read_timeout 5s;
          proxy_set_header Host $host;
          proxy_ignore_headers Cache-Control;

          proxy_cache_revalidate on;
          proxy_cache_use_stale error timeout http_500 http_502 http_503 http_504;
          proxy_cache_lock on;

          proxy_buffering on;
          proxy_buffers 256 4k;
          proxy_max_temp_file_size 0k;

          proxy_cache_valid 200 30m;
          proxy_cache_valid any 0s;
        }
      }
    }

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "sanfran.fullname" . }}
  labels:
    app: {{ template "sanfran.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ template "sanfran.fullname" . }}
  replicas: {{ .Values.fnstoreCache.instances }}
  template:
    metadata:
      labels:
        app: {{ template "sanfran.fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: nginx
          image: nginx:alpine
          securityContext:
            #allowPrivilegeEscalation: false
            #readOnlyRootFilesystem: true
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: cache-volume
              mountPath: /var/cache/nginx
            - name: nginx-conf
              mountPath: /etc/nginx
      volumes:
        - name: cache-volume
          emptyDir:
            medium: "Memory"
            sizeLimit: "100Mi"
        - name: nginx-conf
          configMap:
            name: {{ template "sanfran.fullname" . }}-cm