## Routing Layer

apiVersion: v1
kind: Service
metadata:
  name: sanfran-routing-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: sanfran-router

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sanfran-router
spec:
  selector:
    matchLabels:
      app: sanfran-router
  replicas:  {{ .Values.router.instances }}
  template:
    metadata:
      labels:
        app: sanfran-router
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: sanfran-router
          image: dosco/sanfran-router:{{ .Values.router.tag }}
          securityContext:
            #allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          ports:
            - name: grpc
              containerPort: 8080
          env:
            - name: SANFRAN_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
